### ISSUE TITLE
🐛  Add `.env` to client as well.

### ISSUE THREAD

**Issue by kairavkkp** [harshil-darji/spotified#1]
Similar to `server` also add support for `.env` file for `client`. 

Variables needed:
1) REACT_SPOTIFY_CLIENT_ID
2) REACT_SERVER_HOST_URL

**Comment by harshil-darji** [comment]
Solved in [commit](https://github.com/harshil-darji/spotified/commit/81af29cc977c85d8347d25d1d77fa01bd567f61c).
